# Generated by Django 3.2.25 on 2025-11-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_tex',
            new_name='question_text',
        ),
    ]
